version: '3.2'

services:
  gateway-app:
    image: gateway-app:v1
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    container_name: gateway-app
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod
    volumes:
      - ./log:/var/log/gateway-service
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s