spring:
  application:
    name: todo-app-gateway-service
  cloud:
    gateway:
      enabled: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
# override from env SPRING_APPLICATION_JSON (здесь json с переопределением нужных свойств)
              - "*"
            allowedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
management:
  endpoints:
    web:
      exposure:
        include: health,gateway,metrics
# Кастомные свойства, не связаны с конфигурационными св-вами resilience4j
circuitbreaker:
  slidingWindowSize: 10
  minimumNumberOfCalls: 10
  slowCallDurationThresholdMillis: 15000
logging:
  level:
    root: INFO
    io:
      github:
        resilience4j:
          circuitbreaker:
            internal: DEBUG
    ru:
      lappi:
        gateway: DEBUG
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
  logback:
    rollingpolicy:
      max-file-size: 100MB
  file:
    name: "${user.dir}/log/gateway-service.log"
server:
  port: 8080
api:
  access-token-header-code: X-Access-Token
  # Внешнее по отношению к gateway
  external:
    auth:
      base-url: http://localhost:8887
      path:
        base: /auth-api
        login: ${api.external.auth.path.base}/login
        validate-token: ${api.external.auth.path.base}/validateToken
        refresh-token: ${api.external.auth.path.base}/refreshToken
    users:
      base-url: http://localhost:8082
      path:
        base: /users-api
        register: ${api.external.users.path.base}/users/register
    notes:
      base-url: http://localhost:8222
      path:
        base: /notes-api
    graphql:
      base-url: http://localhost:8333
      path:
        base: /graphql

  routes:
    gateway-base-path: /todo-web-api
    validate-token-url: ${api.external.auth.base-url}${api.external.auth.path.validate-token}